export const catchErrors = (errors, apiName) => {
  console.log('error caught in catch block', errors, apiName)

  //handle error here
}
